### PR TITLE
Build executables conditionally on features

### PR DESCRIPTION
**Pull request by dpwiz**
Maybe something common like "build-examples" or "development" will be a better fit.

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Would it be ok to disable the examples by default? e.g. i had to carry vulkan because nix insisted on being able to build all the examples.

**Comment by dpwiz** [comment]
The problem here is that the library itself by default will blast unsuspecting users with kitchen sink dependency plan.
On the other hand, building a backend-less library is kinda useless, and users have to add package flags anyway.

**Comment by dpwiz** [comment]
Nevermind, the default flags are glew+sdl. And I added `examples` in default-off mode.

I would like, however, to have haddocks uploaded with all the backends so one can use hackage documentation right away.

**Comment by ocharles** [comment]
This LGTM, thanks!

**Pull request merged**
