### PR TITLE
Update all flags to allow setting them manually

### PR DESCRIPTION
**Pull request by sheaf**

### CODE REVIEW

**Review by TristanCacqueray — COMMENTED** [review]
It's a bit annoying to have to disable all the un-necessary backend. What is the purpose of that change?

**Comment by sheaf** [comment]
This doesn't mean the will be on by default, this means they can be turned off manually instead of cabal deciding to turn them off itself.

**Review by TristanCacqueray — APPROVED** [review]

**Comment by TristanCacqueray** [comment]
My bad I misread, thanks, that looks good to me :-)

**Review by dpwiz — APPROVED** [review]

**Comment by dpwiz** [comment]
If I understood its docs correctly, that means cabal wouldn't flip them either way when trying to solve dependencies.

**Pull request merged**
