### PR TITLE
Add support for GLFW

### PR DESCRIPTION
**Pull request by bflyblue**
I've only tested this on Windows with OpenGL (example included).

I'm not sure why but I needed to use `pkgconfig-depends: glfw3` to get linking to work using Chocolatey although `extra-libraries` is sufficient to SDL2 to link. For reference, I used to following to install the dependencies:

```powershell
mingw64-pkg.bat install pkg-config
mingw64-pkg.bat install SDL2
mingw64-pkg.bat install glfw
```

### CODE REVIEW

**Comment by bflyblue** [comment]
From what I understand from the [GLFW Build Guide](https://www.glfw.org/docs/latest/build_guide.html) we don't actually have to link against `glfw3` at all on windows unless you want use the static version. I've tried adding the following on my windows environment and it works as expected:

```patch
-    pkgconfig-depends:
-      glfw3
+    if os(linux) || os(darwin)
+      pkgconfig-depends:
+        glfw3
```

**Comment by TristanCacqueray** [comment]
It seems like haskell.nix doesn't pull libXext when installing GLFW-b. Looking at nixpkgs package set, the binding-GLFW somehow has a bunch of librarySystemDepends based on https://github.com/NixOS/nixpkgs/blob/09c2f74a31b75691dbcaaca2619b7387b0135358/pkgs/development/haskell-modules/configuration-nix.nix#L426-L435 . @ocharles , how can we fix that? 

Otherwise, that PR seems to work, thanks!

**Comment by ocharles** [comment]
As we're used by Haskell.nix it'll be a bit different - but I can take a look!

**Comment by bflyblue** [comment]
Out of interest, is there a preference for using Haskell.nix rather than standard nixpkgs?

**Comment by TristanCacqueray** [comment]
Actually, the necessary librarySystemDepends are defined in the generated haskell-package.nix, and i can't tell if this is a nixpkgs workaround that can be added to Haskell.nix, or if it's something we can cherry-pick in dear-imgui.

If I understand correctly, Haskell.nix is better at managing build-depends versions, and perhaps it's necessary for vulkan libraries?

**Comment by ocharles** [comment]
Ok, I think I got everything working. @bflyblue I'm assuming you're not using Nix on windows? I think my fix might be Linux-specific, but I think for now that'll be OK. If anyone uses Nix & Darwin, perhaps you can try

**Comment by bflyblue** [comment]
> Ok, I think I got everything working. @bflyblue I'm assuming you're not using Nix on windows? I think my fix might be Linux-specific, but I think for now that'll be OK. If anyone uses Nix & Darwin, perhaps you can try

Running a build now on my Catalina + Nix macbook and will report back.

**Comment by bflyblue** [comment]
> Running a build now on my Catalina + Nix macbook and will report back.

It's failing to build `bindings-GLFW-3.3.2.0`:

```
glfw/src/cocoa_joystick.m:40:10: error:
     fatal error: 'Kernel/IOKit/hidsystem/IOHIDUsageTables.h' file not found
   |
40 | #include <Kernel/IOKit/hidsystem/IOHIDUsageTables.h>
   |          ^
#include <Kernel/IOKit/hidsystem/IOHIDUsageTables.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
`cc' failed in phase `C Compiler'. (Exit code: 1)
```

**Comment by bflyblue** [comment]
Using standard `nixpkgs` instead of `haskell.nix` does compile fine on OSX (minus the vulkan stuff since I believe there's no native vulkan support on OS X)

**Comment by ocharles** [comment]
I can only test on Linux, but this works for me! I don't want to hold this up any longer, we can always work on other platform Nix packaging if necessary later. Thanks for the great work, @bflyblue!

**Pull request merged**
