### PR TITLE
Add withFullscreen wrapper for begin

### PR DESCRIPTION
**Pull request by dpwiz**
The code combines getting current window size with setting a position and a bunch of flags to get window suitable for "UI-only" apps.

### CODE REVIEW

**Review by TristanCacqueray — APPROVED** [review]
:+1:

**Comment by ocharles** [comment]
This seems rather involved for something that lives in the "raw" bindings.

**Comment by dpwiz** [comment]
As I see it, `Raw` functions are as-thin-as-possible wrappers over upstream C code.
This appears to match yours.

In this particular case, I the Raw part is mostly driven by `SetNextWindowSize(GetIO().DisplaySize);` fusion.

Thinking about it again, perhaps it would be better to just add `displaySize` raw and route everything else via Haskell. The Fullscreen flags can be a simple pattern.

**Comment by ocharles** [comment]
Yea, that's what I'm thinking.

**Pull request closed without merging**
