### PR TITLE
Add withXxx and withXxxOpen wrappers for begin/end pairs

### LINKED ISSUE #32: Handling of Begin/End pairs
Is there any situation in which users might need to use `beginXXX`/`endXXX` in an atypical way? As far as I understand:

- `begin`/`end`, `beginChild`/`endChild`, `beginGroup`/`endGroup`, `beginTooltip`/`endTooltip`, `beginChildFrame`/`endChildFrame` must always occur in matching pairs, so we can replace them with simple `with`-style functions,
- `beginCombo`/`endCombo`, `beginListBox`/`endListBox`,  `beginMenuBar`/`endMenuBar`, `beginMainMenuBar`/`endMainMenuBar`, `beginPopup`/`endPopup`, `beginTable`/`endTable`, `beginTabBar`/`endTabBar`, `beginDragDropSource`/`endDragDropSource`, `beginDragDropTarget`/`endDragDropTarget` all require a matching `end` function precisely when the `begin` function returned `True`. Is there any other way to use them than with the `whenTrue` idiom we are currently using in the example?

If there is literally no other valid usage pattern, I would recommend entirely replacing the `beginXXX`/`endXXX` functions with bracketed functions. Then users aren't confused about which one to use, and can't get it wrong.    
If there are valid usage patterns, then of course we should keep the individual `beginXXX`/`endXXX` functions, and provide additional helpers.

### PR DESCRIPTION
**Pull request by dpwiz**
Fixes #32

### CODE REVIEW

**Comment by ocharles** [comment]
I think these should be documented that they don't do any exception handling, because right now they might lull the reader into a false sense of security.

**Comment by dpwiz** [comment]
I started to spell this out and become dissatisfied with this resolution.
It's not too late to adopt `unliftio` and do the right thing instead.

**Comment by ocharles** [comment]
I have no objection to using `MonadUnliftIO`.

**Review by TristanCacqueray — APPROVED** [review]
That seems to work as expected: https://github.com/TristanCacqueray/dear-filedialog.hs/commit/bff91ac32cee9a80165435a048d907f78e8e931d

**Comment by dpwiz** [comment]
I've checked on my project with multiple windows and tabs. The code is improved and nothing seems broken :sweat_smile:

**Pull request merged**
